AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - Rakefile

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/OptionalArguments:
  Exclude:
    - 'lib/controller/**/*'
